// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;
using SoccerTv.Api.Data;

#nullable disable

namespace SoccerTv.Api.Migrations
{
    [DbContext(typeof(SoccerTvDbContext))]
    [Migration("20260925152012_FlattenFixtures")]
    partial class FlattenFixtures
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SoccerTv.Api.Data.Fixtures.Fixture", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AwayTeam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("away_team");

                    b.Property<string>("Competition")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("competition");

                    b.Property<int>("CompetitionSortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("competition_sort_order");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("HomeTeam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("home_team");

                    b.Property<DateTimeOffset>("KickoffUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("kickoff_utc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_fixtures");

                    b.HasIndex(new[] { "Competition" }, "ix_fixtures_competition");

                    b.HasIndex(new[] { "KickoffUtc" }, "ix_fixtures_kickoff_utc");

                    b.HasIndex(new[] { "Source", "ExternalId" }, "ix_fixtures_source_external_id")
                        .IsUnique();

                    b.ToTable("fixtures", (string)null);
                });

            modelBuilder.Entity("SoccerTv.Api.Data.Schedule.UserFixture", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("FixtureId")
                        .HasColumnType("uuid")
                        .HasColumnName("fixture_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.HasKey("UserId", "FixtureId")
                        .HasName("pk_user_fixtures");

                    b.HasIndex("FixtureId");

                    b.ToTable("user_fixtures", (string)null);
                });

            modelBuilder.Entity("SoccerTv.Api.Data.Users.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("CalendarFeedToken")
                        .HasColumnType("text")
                        .HasColumnName("calendar_feed_token");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date")
                        .HasColumnName("date_of_birth");

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_address");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsLockedOut")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_locked_out");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<string>("NormalizedEmailAddress")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("text")
                        .HasColumnName("normalized_email_address")
                        .HasComputedColumnSql("lower(email_address)", true);

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text")
                        .HasColumnName("password_reset_token");

                    b.Property<int>("ReminderMinutesBefore")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(30)
                        .HasColumnName("reminder_minutes_before");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "FirstName", "LastName", "EmailAddress" });

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex(new[] { "CalendarFeedToken" }, "ix_users_calendar_feed_token")
                        .IsUnique();

                    b.HasIndex(new[] { "NormalizedEmailAddress" }, "ix_users_normalized_email_address")
                        .IsUnique();

                    b.HasIndex(new[] { "SearchVector" }, "ix_users_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex(new[] { "SearchVector" }, "ix_users_search_vector"), "gin");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SoccerTv.Api.Data.Fixtures.Fixture", b =>
                {
                    b.OwnsMany("SoccerTv.Api.Data.Fixtures.FixtureChannel", "Channels", b1 =>
                        {
                            b1.Property<Guid>("FixtureId");

                            b1.Property<int>("__synthesizedOrdinal")
                                .ValueGeneratedOnAdd();

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasJsonPropertyName("name");

                            b1.Property<string>("Provider")
                                .IsRequired()
                                .HasJsonPropertyName("provider");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasJsonPropertyName("type");

                            b1.HasKey("FixtureId", "__synthesizedOrdinal");

                            b1.ToTable("fixtures");

                            b1
                                .ToJson("channels")
                                .HasColumnType("jsonb");

                            b1.WithOwner()
                                .HasForeignKey("FixtureId");
                        });

                    b.Navigation("Channels");
                });

            modelBuilder.Entity("SoccerTv.Api.Data.Schedule.UserFixture", b =>
                {
                    b.HasOne("SoccerTv.Api.Data.Fixtures.Fixture", "Fixture")
                        .WithMany()
                        .HasForeignKey("FixtureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_fixtures_fixtures_fixture_id");

                    b.HasOne("SoccerTv.Api.Data.Users.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_fixtures_users_user_id");

                    b.Navigation("Fixture");

                    b.Navigation("User");
                });
#pragma warning restore 612, 618
        }
    }
}
